/**
 * KeyCascade — Aesthetic Themes & Color Presets
 * Developed by Alon Ashkenazi
 */

import { ThemePreset } from '../types/visualizer';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'amethyst-stardust',
    name: 'Amethyst & Magenta Stardust',
    description: 'Faceted crystal diamond notes with swirling stardust dissolve & magenta aura',
    noteStyle: 'crystal',
    dissolveMode: 'stardust',
    leftHandColor: '#9333ea',
    leftHandSecondary: '#c084fc',
    rightHandColor: '#f43f5e',
    rightHandSecondary: '#fb7185',
    saberColor: '#d946ef',
    saberGlow: '#a855f7',
    bgMode: 'black',
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    description: 'Electric Cyan Bass & Radiant Magenta Treble with high-intensity bloom',
    noteStyle: 'neon',
    dissolveMode: 'sparks',
    leftHandColor: '#00f2fe',
    leftHandSecondary: '#4facfe',
    rightHandColor: '#ff007f',
    rightHandSecondary: '#b153ff',
    saberColor: '#00f2fe',
    saberGlow: '#00f2fe',
    bgMode: 'black',
  },
  {
    id: 'cosmic-nebula',
    name: 'Cosmic Nebula Smoke',
    description: 'Deep violet tones with ethereal billowing cosmic nebula smoke',
    noteStyle: 'glass',
    dissolveMode: 'smoke',
    leftHandColor: '#7c3aed',
    leftHandSecondary: '#a78bfa',
    rightHandColor: '#ec4899',
    rightHandSecondary: '#f472b6',
    saberColor: '#c084fc',
    saberGlow: '#a855f7',
    bgMode: 'black',
  },
  {
    id: 'rousseau-fire',
    name: 'Solar Flare & Sparks',
    description: 'Molten Gold & Solar Flare Orange with explosive spark fountains',
    noteStyle: 'crystal',
    dissolveMode: 'sparks',
    leftHandColor: '#ff9900',
    leftHandSecondary: '#ff5500',
    rightHandColor: '#ff2255',
    rightHandSecondary: '#ffbb00',
    saberColor: '#ffaa00',
    saberGlow: '#ff5500',
    bgMode: 'black',
  },
  {
    id: 'emerald-aurora',
    name: 'Emerald Aurora',
    description: 'Ethereal Mint Glow & Vivid Emerald Neon with cosmic green saber line',
    noteStyle: 'crystal',
    dissolveMode: 'stardust',
    leftHandColor: '#00f5a0',
    leftHandSecondary: '#00d9f5',
    rightHandColor: '#10b981',
    rightHandSecondary: '#34d399',
    saberColor: '#00f5a0',
    saberGlow: '#00d9f5',
    bgMode: 'black',
  },
  {
    id: 'ice-sapphire',
    name: 'Ice & Sapphire',
    description: 'Glacial White-Blue & Deep Ultramarine crystal',
    noteStyle: 'glass',
    dissolveMode: 'stardust',
    leftHandColor: '#38ef7d',
    leftHandSecondary: '#11998e',
    rightHandColor: '#00c6ff',
    rightHandSecondary: '#0072ff',
    saberColor: '#00c6ff',
    saberGlow: '#0072ff',
    bgMode: 'black',
  },
  {
    id: 'obsidian-magma',
    name: '🔥 Molten Obsidian & Magma',
    description: 'Polished mirror obsidian stones with glowing molten magma fissures & solar embers',
    noteStyle: 'obsidian',
    dissolveMode: 'stardust',
    leftHandColor: '#ff4500',
    leftHandSecondary: '#ff8c00',
    rightHandColor: '#ffd700',
    rightHandSecondary: '#ff3b00',
    saberColor: '#ff8c00',
    saberGlow: '#ff2200',
    bgMode: 'black',
  },
  {
    id: 'minimal-monochrome',
    name: 'Studio Minimal',
    description: 'Clean Ivory & Platinum with subtle cyan aura (Clean YouTube overlay)',
    noteStyle: 'minimal',
    dissolveMode: 'off',
    leftHandColor: '#94a3b8',
    leftHandSecondary: '#cbd5e1',
    rightHandColor: '#f8fafc',
    rightHandSecondary: '#e2e8f0',
    saberColor: '#ffffff',
    saberGlow: '#38bdf8',
    bgMode: 'black',
  },
];
