/**
 * KeyCascade — Aesthetic Themes & Color Presets
 * Developed by Alon Ashkenazi
 */

import { ThemePreset } from '../types/visualizer';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'grim-cat-amethyst',
    name: 'Grim Cat Amethyst & Dust',
    description: 'Faceted crystal diamond notes with swirling stardust dissolve & magenta aura (As seen on YouTube)',
    noteStyle: 'crystal',
    dissolveMode: 'stardust',
    leftHandColor: '#9333ea',
    leftHandSecondary: '#c084fc',
    rightHandColor: '#f43f5e',
    rightHandSecondary: '#fb7185',
    saberColor: '#d946ef',
    saberGlow: '#a855f7',
    bgMode: 'black',
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    description: 'Electric Cyan Bass & Radiant Magenta Treble with high-intensity bloom (Classic Rousseau)',
    noteStyle: 'neon',
    dissolveMode: 'sparks',
    leftHandColor: '#00f2fe',
    leftHandSecondary: '#4facfe',
    rightHandColor: '#ff007f',
    rightHandSecondary: '#b153ff',
    saberColor: '#00f2fe',
    saberGlow: '#00f2fe',
    bgMode: 'black',
  },
  {
    id: 'rousseau-fire',
    name: 'Rousseau Fire & Gold',
    description: 'Molten Gold & Solar Flare Orange with burning strike particles',
    noteStyle: 'crystal',
    dissolveMode: 'sparks',
    leftHandColor: '#ff9900',
    leftHandSecondary: '#ff5500',
    rightHandColor: '#ff2255',
    rightHandSecondary: '#ffbb00',
    saberColor: '#ffaa00',
    saberGlow: '#ff5500',
    bgMode: 'black',
  },
  {
    id: 'emerald-aurora',
    name: 'Emerald Aurora',
    description: 'Ethereal Mint Glow & Vivid Emerald Neon with cosmic green saber line',
    noteStyle: 'crystal',
    dissolveMode: 'stardust',
    leftHandColor: '#00f5a0',
    leftHandSecondary: '#00d9f5',
    rightHandColor: '#10b981',
    rightHandSecondary: '#34d399',
    saberColor: '#00f5a0',
    saberGlow: '#00d9f5',
    bgMode: 'black',
  },
  {
    id: 'ice-sapphire',
    name: 'Ice & Sapphire',
    description: 'Glacial White-Blue & Deep Ultramarine crystal',
    noteStyle: 'glass',
    dissolveMode: 'stardust',
    leftHandColor: '#38ef7d',
    leftHandSecondary: '#11998e',
    rightHandColor: '#00c6ff',
    rightHandSecondary: '#0072ff',
    saberColor: '#00c6ff',
    saberGlow: '#0072ff',
    bgMode: 'black',
  },
  {
    id: 'minimal-monochrome',
    name: 'Studio Minimal',
    description: 'Clean Ivory & Platinum with subtle cyan aura (Clean YouTube overlay)',
    noteStyle: 'minimal',
    dissolveMode: 'off',
    leftHandColor: '#94a3b8',
    leftHandSecondary: '#cbd5e1',
    rightHandColor: '#f8fafc',
    rightHandSecondary: '#e2e8f0',
    saberColor: '#ffffff',
    saberGlow: '#38bdf8',
    bgMode: 'black',
  },
];
